apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metadata-broker-open-core.fullname" . }}
data:
  ADMIN_PASSWORD: {{ .Values.env.secret.ADMIN_PASSWORD | b64enc }}
  {{- if .Values.broker.truststore.p12 }}
  truststore: {{ .Values.broker.truststore.p12 | b64enc }}
  truststore_password: {{ .Values.broker.truststore.password | b64enc }}
  {{- end }}
  